name: Create Release Branch from Tag

on:
  release:
    types: [published]

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    if: github.event.release.tag_name != 'latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Determine branch name
        id: determine_branch
        run: |
          TAG_NAME="${{ steps.get_tag.outputs.TAG_NAME }}"
          BRANCH_NAME="release/${TAG_NAME}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create branch
        run: |
          BRANCH_NAME="${{ steps.determine_branch.outputs.BRANCH_NAME }}"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
